### ISSUE TITLE
Migration to Developers Italia

### ISSUE THREAD

**Issue by peppelinux** [psmiraglia/spid-compliant-certificates#4]
Dear Paolo,
Considering the quality of this repository in relation to the promulgation objectives of the tools currently useful to simplify the SPID accreditation process, and all its intermediate steps, I would like to ask you to migrate this repository to developers italia.

We could address any requests for integration of CI models, if you agree, once the repository has been migrated. You will remain the one and only maintainer.

Sure of your kind reply,
thank you for what has been done to date

**Comment by psmiraglia** [comment]
It's fine! I'll give you all the required permissions to migrate the repo.
